"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import styles from "./vote.module.css";

type Question={id:number;title:string;stem:string;options:string[];correctAnswer:number;createdAt:string};
type Results={question:Question;counts:number[];total:number};
const letters=["a","b","c","d","e","f"];
function deviceId(){const key="votacoes-clinicas-device";let id=localStorage.getItem(key);if(!id){id=crypto.randomUUID();localStorage.setItem(key,id)}return id}

export default function Home(){
 const [mode,setMode]=useState<"home"|"new"|"vote"|"panel">("home"); const [questions,setQuestions]=useState<Question[]>([]);const [question,setQuestion]=useState<Question|null>(null);const [results,setResults]=useState<Results|null>(null);const [form,setForm]=useState({title:"",stem:"",options:["","","",""],correctAnswer:0});const [selected,setSelected]=useState<number|null>(null);const [message,setMessage]=useState("");
 const query=useMemo(()=>typeof window!=="undefined"?new URLSearchParams(window.location.search):null,[]);const questionId=query?.get("q");const isPanel=query?.get("painel")==="1";
 const loadQuestions=useCallback(async()=>{const r=await fetch("/api/questions",{cache:"no-store"});if(r.ok){const j=await r.json();setQuestions(j.questions)}},[]);
 const loadQuestion=useCallback(async(id:string)=>{const r=await fetch(`/api/questions/${id}`,{cache:"no-store"});if(r.ok){const j=await r.json();setQuestion(j.question)}},[]);
 const loadResults=useCallback(async(id:string)=>{const r=await fetch(`/api/questions/${id}/results`,{cache:"no-store"});if(r.ok){const j=await r.json();setResults(j);setQuestion(j.question)}},[]);
 useEffect(()=>{if(questionId){setMode(isPanel?"panel":"vote");if(isPanel)loadResults(questionId);else loadQuestion(questionId)}else loadQuestions()},[questionId,isPanel,loadQuestions,loadQuestion,loadResults]);
 useEffect(()=>{if(mode!=="panel"||!questionId)return;const t=setInterval(()=>loadResults(questionId),5000);return()=>clearInterval(t)},[mode,questionId,loadResults]);
 async function create(event:FormEvent){event.preventDefault();setMessage("");const r=await fetch("/api/questions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await r.json();if(!r.ok){setMessage(data.error);return}window.location.href=`?q=${data.question.id}&painel=1`}
 async function vote(){if(selected===null||!questionId)return;const r=await fetch(`/api/questions/${questionId}/vote`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answerIndex:selected,deviceId:deviceId()})});const data=await r.json();setMessage(r.ok?"Resposta registrada! Aguarde a discussão da turma.":data.error)}
 async function reset(){if(!questionId||!confirm("Zerar todas as respostas desta questão?"))return;await fetch(`/api/questions/${questionId}/results`,{method:"DELETE"});loadResults(questionId)}
 const addOption=()=>setForm({...form,options:[...form.options,""]});
 if(mode==="new")return <main className={styles.shell}><section className={styles.card}><header><span className={styles.kicker}>NOVA QUESTÃO</span><button className={styles.link} onClick={()=>setMode("home")}>← Voltar</button></header><form className={styles.form} onSubmit={create}><label>Título curto<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ex.: Necrose cerebral" required/></label><label>Enunciado<textarea value={form.stem} onChange={e=>setForm({...form,stem:e.target.value})} placeholder="Digite o caso clínico ou a pergunta" required/></label><fieldset><legend>Alternativas e resposta correta</legend>{form.options.map((option,index)=><div className={styles.optionInput} key={index}><input type="radio" name="correct" checked={form.correctAnswer===index} onChange={()=>setForm({...form,correctAnswer:index})}/><span>{letters[index]})</span><input value={option} onChange={e=>{const options=[...form.options];options[index]=e.target.value;setForm({...form,options})}} placeholder={`Alternativa ${letters[index]}`} required/></div>)}{form.options.length<6&&<button type="button" className={styles.add} onClick={addOption}>+ Adicionar alternativa</button>}</fieldset><button className={styles.primary}>Criar questão e QR Code</button>{message&&<p className={styles.error}>{message}</p>}</form></section></main>;
 if(mode==="panel"&&results){const url=typeof window!=="undefined"?`${window.location.origin}?q=${results.question.id}`:"";return <main className={styles.shell}><section className={styles.dashboard}><header><div><span className={styles.kicker}>PAINEL DO PROFESSOR</span><h1>{results.question.title}</h1><p>Atualiza automaticamente a cada 5 segundos.</p></div><div className={styles.actions}><button className={styles.danger} onClick={reset}>Zerar votação</button><b className={styles.total}>{results.total}<small>respostas</small></b></div></header><div className={styles.grid}><aside className={styles.qr}><span className={styles.kicker}>ENTRADA DA TURMA</span><img src={`https://api.qrserver.com/v1/create-qr-code/?size=420x420&margin=12&data=${encodeURIComponent(url)}`} alt="QR Code da questão"/><code>{url}</code></aside><article className={styles.results}><span className={styles.kicker}>DISTRIBUIÇÃO</span>{results.question.options.map((option,index)=>{const count=results.counts[index];const pct=results.total?Math.round(count/results.total*100):0;return <div className={styles.bar} key={option}><div><b>{letters[index]}) {option}</b><span>{count} · {pct}%</span></div><i><em className={index===results.question.correctAnswer?styles.correct:""} style={{width:`${pct}%`}}/></i></div>})}<p className={styles.answer}>Resposta correta: <strong>{letters[results.question.correctAnswer]}) {results.question.options[results.question.correctAnswer]}</strong></p></article></div></section></main>}
 if(mode==="vote"&&question)return <main className={styles.shell}><section className={styles.card}><header><span className={styles.kicker}>VOTAÇÃO CLÍNICA</span><span>Patologia</span></header><article className={styles.question}><h1>{question.title}</h1><p>{question.stem}</p><div className={styles.choices}>{question.options.map((option,index)=><button disabled={message.startsWith("Resposta")} onClick={()=>{setSelected(index);setMessage("")}} className={selected===index?styles.selected:""} key={option}><b>{letters[index]}</b>{option}</button>)}</div><button className={styles.primary} onClick={vote}>Confirmar resposta</button>{message&&<p className={message.startsWith("Resposta")?styles.success:styles.error}>{message}</p>}</article></section></main>;
 return <main className={styles.shell}><section className={styles.dashboard}><header><div><span className={styles.kicker}>VOTAÇÕES CLÍNICAS</span><h1>Questões que envolvem a turma.</h1><p>Crie uma pergunta, projete o QR Code e acompanhe a distribuição das respostas.</p></div><button className={styles.primary} onClick={()=>setMode("new")}>+ Nova questão</button></header><div className={styles.list}>{questions.length?questions.map(q=><a key={q.id} href={`?q=${q.id}&painel=1`}><span className={styles.kicker}>QUESTÃO {q.id}</span><b>{q.title}</b><small>Abrir painel e QR Code →</small></a>):<div className={styles.empty}>Ainda não há questões. Crie a primeira para começar.</div>}</div></section></main>
}
