"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import styles from "./vote.module.css";
type Question={id:number;title:string;stem:string;options:string[];correctAnswer:number;imageUrl?:string|null};
type Results={question:Question;counts:number[];total:number}; const letters=["a","b","c","d","e","f"];
function deviceId(){const k="votacoes-clinicas-device";let id=localStorage.getItem(k);if(!id){id=crypto.randomUUID();localStorage.setItem(k,id)}return id}
export default function Home(){const [mode,setMode]=useState<"home"|"new"|"vote"|"panel">("home"),[questions,setQuestions]=useState<Question[]>([]),[question,setQuestion]=useState<Question|null>(null),[results,setResults]=useState<Results|null>(null),[selected,setSelected]=useState<number|null>(null),[message,setMessage]=useState("");const [form,setForm]=useState({title:"",stem:"",imageUrl:"",options:["","","",""],correctAnswer:0});const query=useMemo(()=>typeof window!=="undefined"?new URLSearchParams(location.search):null,[]),id=query?.get("q"),panel=query?.get("painel")==="1";
const load=useCallback(async()=>{const r=await fetch("/api/questions");if(r.ok)setQuestions((await r.json()).questions)},[]);const loadQ=useCallback(async(q:string)=>{const r=await fetch(`/api/questions/${q}`);if(r.ok)setQuestion((await r.json()).question)},[]);const loadR=useCallback(async(q:string)=>{const r=await fetch(`/api/questions/${q}/results`);if(r.ok){const data=await r.json();setResults(data);setQuestion(data.question)}},[]);
useEffect(()=>{if(id){setMode(panel?"panel":"vote");panel?loadR(id):loadQ(id)}else load()},[id,panel,load,loadQ,loadR]);useEffect(()=>{if(!panel||!id)return;const t=setInterval(()=>loadR(id),5000);return()=>clearInterval(t)},[id,panel,loadR]);
async function create(e:FormEvent){e.preventDefault();const r=await fetch("/api/questions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)return setMessage(d.error);location.href=`?q=${d.question.id}&painel=1`};async function vote(){if(selected===null||!id)return;const r=await fetch(`/api/questions/${id}/vote`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answerIndex:selected,deviceId:deviceId()})}),d=await r.json();setMessage(r.ok?"Resposta registrada! Aguarde a discussão da turma.":d.error)};async function reset(){if(id&&confirm("Zerar todas as respostas desta questão?")){await fetch(`/api/questions/${id}/results`,{method:"DELETE"});loadR(id)}};
if(mode==="new")return <main className={styles.shell}><section className={styles.card}><header><span className={styles.kicker}>NOVA QUESTÃO</span><button className={styles.link} onClick={()=>setMode("home")}>← Voltar</button></header><form className={styles.form} onSubmit={create}><label>Título curto<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Enunciado<textarea required value={form.stem} onChange={e=>setForm({...form,stem:e.target.value})}/></label><label>URL da imagem (opcional)<input value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/></label><fieldset><legend>Alternativas e resposta correta</legend>{form.options.map((o,i)=><div className={styles.optionInput} key={i}><input type="radio" name="correct" checked={form.correctAnswer===i} onChange={()=>setForm({...form,correctAnswer:i})}/><span>{letters[i]})</span><input required value={o} onChange={e=>{const options=[...form.options];options[i]=e.target.value;setForm({...form,options})}}/></div>)}</fieldset><button className={styles.primary}>Criar questão e QR Code</button>{message&&<p className={styles.error}>{message}</p>}</form></section></main>;
if(mode==="panel"&&results){const url=`${location.origin}?q=${results.question.id}`;return <main className={styles.shell}><section className={styles.dashboard}><header><div><span className={styles.kicker}>PAINEL DO PROFESSOR</span><h1>{results.question.title}</h1><p>Atualiza automaticamente a cada 5 segundos.</p></div><div className={styles.actions}><button className={styles.danger} onClick={reset}>Zerar votação</button><b className={styles.total}>{results.total}<small>respostas</small></b></div></header><div className={styles.grid}><aside className={styles.qr}><span className={styles.kicker}>ENTRADA DA TURMA</span><img src={`https://api.qrserver.com/v1/create-qr-code/?size=420x420&margin=12&data=${encodeURIComponent(url)}`} alt="QR Code"/><code>{url}</code></aside><article className={styles.results}><span className={styles.kicker}>DISTRIBUIÇÃO</span>{results.question.options.map((o,i)=>{const n=results.counts[i],p=results.total?Math.round(n/results.total*100):0;return <div className={styles.bar} key={o}><div><b>{letters[i]}) {o}</b><span>{n} · {p}%</span></div><i><em className={i===results.question.correctAnswer?styles.correct:""} style={{width:`${p}%`}}/></i></div>})}<p className={styles.answer}>Resposta correta: <strong>{letters[results.question.correctAnswer]}) {results.question.options[results.question.correctAnswer]}</strong></p></article></div></section></main>}
if(mode==="vote"&&question)return <main className={styles.shell}><section className={styles.card}><header><span className={styles.kicker}>VOTAÇÃO CLÍNICA</span><span>Patologia</span></header><article className={styles.question}><h1>{question.title}</h1><p>{question.stem}</p>{question.imageUrl&&<img className={styles.micrograph} src={question.imageUrl} alt="Fotomicrografia da questão"/>}<div className={styles.choices}>{question.options.map((o,i)=><button disabled={message.startsWith("Resposta")} className={selected===i?styles.selected:""} onClick={()=>{setSelected(i);setMessage("")}} key={o}><b>{letters[i]}</b>{o}</button>)}</div><button className={styles.primary} onClick={vote}>Confirmar resposta</button>{message&&<p className={message.startsWith("Resposta")?styles.success:styles.error}>{message}</p>}</article></section></main>;
return <main className={styles.shell}><section className={styles.dashboard}><header><div><span className={styles.kicker}>VOTAÇÕES CLÍNICAS</span><h1>Questões que envolvem a turma.</h1><p>Crie uma pergunta, projete o QR Code e acompanhe a distribuição.</p></div><button className={styles.primary} onClick={()=>setMode("new")}>+ Nova questão</button></header><div className={styles.list}>{questions.length?questions.map(q=><a key={q.id} href={`?q=${q.id}&painel=1`}><span className={styles.kicker}>QUESTÃO {q.id}</span><b>{q.title}</b><small>Abrir painel e QR Code →</small></a>):<div className={styles.empty}>Ainda não há questões. Crie a primeira para começar.</div>}</div></section></main>}
